export enum Rol {
  CLIENTE = 'CLIENTE',
  ADMINISTRADOR = 'ADMINISTRADOR',
  GESTOR_PRODUCTOS = 'GESTOR_PRODUCTOS',
  SUPERVISOR_PRODUCCION = 'SUPERVISOR_PRODUCCION',
  ENCARGADO_ALMACEN = 'ENCARGADO_ALMACEN'
}
