export enum TipoProducto {
  MAQUILLAJE = 'MAQUILLAJE',
  CUIDADO_PIEL = 'CUIDADO_PIEL',
  CABELLO = 'CABELLO',
  FRAGANCIAS = 'FRAGANCIAS',
  TRATAMIENTOS = 'TRATAMIENTOS',
  ACCESORIOS = 'ACCESORIOS'
}